add_requires("catch2")
add_requires("cli11")
add_requires("openmp")

target("0305")
    set_languages("cxxlatest")
    set_kind("binary")
    add_deps("dcs229.common")
    add_packages("cli11", "openmp")
    add_files("src/**.cu")
    add_headerfiles("src/(**.hpp)")
    add_headerfiles("src/(**.cuh)")
    add_includedirs("src")
    add_cugencodes("native")
    add_cxflags("-mavx2")
    add_cuflags("-Xcompiler", "-mavx2", {force = true})
    -- Run from the repository root so paths given relative to it (e.g.
    -- `0305/tests/data/board.png`) resolve under `xmake r 0305 ...`.
    set_rundir(path.directory(os.scriptdir()))

target("0305.tests")
    set_languages("cxxlatest")
    set_kind("binary")
    add_deps("dcs229.common")
    add_packages("catch2", "openmp")
    add_files("tests/Laplacian_test.cu")
    add_includedirs("src")
    add_cugencodes("native")
    add_cxflags("-mavx2")
    add_cuflags("-Xcompiler", "-mavx2", {force = true})
    add_defines('DCS229_TEST_DATA_DIR="' .. path.join(os.scriptdir(), "tests", "data") .. '"')

target("0305.bench")
    set_languages("cxxlatest")
    set_kind("binary")
    add_deps("dcs229.common")
    add_packages("catch2", "openmp")
    add_files("tests/Laplacian_bench.cu")
    add_includedirs("src")
    add_cugencodes("native")
    add_cxflags("-mavx2")
    add_cuflags("-Xcompiler", "-mavx2", {force = true})
    set_rundir(path.directory(os.scriptdir()))
